rising:
	vcs -sverilog -debug_all -full64 -top tb -f vcs.args +define+RISING
falling:
	vcs -sverilog -debug_all -full64 -top tb -f vcs.args +define+FALLING
pulse:
	vcs -sverilog -debug_all -full64 -top tb -f vcs.args +define+PULSE