
//input ports
add mapped point aclk aclk
add mapped point rst rst
add mapped point input_spikes[63] input_spikes[63]
add mapped point input_spikes[62] input_spikes[62]
add mapped point input_spikes[61] input_spikes[61]
add mapped point input_spikes[60] input_spikes[60]
add mapped point input_spikes[59] input_spikes[59]
add mapped point input_spikes[58] input_spikes[58]
add mapped point input_spikes[57] input_spikes[57]
add mapped point input_spikes[56] input_spikes[56]
add mapped point input_spikes[55] input_spikes[55]
add mapped point input_spikes[54] input_spikes[54]
add mapped point input_spikes[53] input_spikes[53]
add mapped point input_spikes[52] input_spikes[52]
add mapped point input_spikes[51] input_spikes[51]
add mapped point input_spikes[50] input_spikes[50]
add mapped point input_spikes[49] input_spikes[49]
add mapped point input_spikes[48] input_spikes[48]
add mapped point input_spikes[47] input_spikes[47]
add mapped point input_spikes[46] input_spikes[46]
add mapped point input_spikes[45] input_spikes[45]
add mapped point input_spikes[44] input_spikes[44]
add mapped point input_spikes[43] input_spikes[43]
add mapped point input_spikes[42] input_spikes[42]
add mapped point input_spikes[41] input_spikes[41]
add mapped point input_spikes[40] input_spikes[40]
add mapped point input_spikes[39] input_spikes[39]
add mapped point input_spikes[38] input_spikes[38]
add mapped point input_spikes[37] input_spikes[37]
add mapped point input_spikes[36] input_spikes[36]
add mapped point input_spikes[35] input_spikes[35]
add mapped point input_spikes[34] input_spikes[34]
add mapped point input_spikes[33] input_spikes[33]
add mapped point input_spikes[32] input_spikes[32]
add mapped point input_spikes[31] input_spikes[31]
add mapped point input_spikes[30] input_spikes[30]
add mapped point input_spikes[29] input_spikes[29]
add mapped point input_spikes[28] input_spikes[28]
add mapped point input_spikes[27] input_spikes[27]
add mapped point input_spikes[26] input_spikes[26]
add mapped point input_spikes[25] input_spikes[25]
add mapped point input_spikes[24] input_spikes[24]
add mapped point input_spikes[23] input_spikes[23]
add mapped point input_spikes[22] input_spikes[22]
add mapped point input_spikes[21] input_spikes[21]
add mapped point input_spikes[20] input_spikes[20]
add mapped point input_spikes[19] input_spikes[19]
add mapped point input_spikes[18] input_spikes[18]
add mapped point input_spikes[17] input_spikes[17]
add mapped point input_spikes[16] input_spikes[16]
add mapped point input_spikes[15] input_spikes[15]
add mapped point input_spikes[14] input_spikes[14]
add mapped point input_spikes[13] input_spikes[13]
add mapped point input_spikes[12] input_spikes[12]
add mapped point input_spikes[11] input_spikes[11]
add mapped point input_spikes[10] input_spikes[10]
add mapped point input_spikes[9] input_spikes[9]
add mapped point input_spikes[8] input_spikes[8]
add mapped point input_spikes[7] input_spikes[7]
add mapped point input_spikes[6] input_spikes[6]
add mapped point input_spikes[5] input_spikes[5]
add mapped point input_spikes[4] input_spikes[4]
add mapped point input_spikes[3] input_spikes[3]
add mapped point input_spikes[2] input_spikes[2]
add mapped point input_spikes[1] input_spikes[1]
add mapped point input_spikes[0] input_spikes[0]

//output ports
add mapped point output_spikes[63] output_spikes[63]
add mapped point output_spikes[62] output_spikes[62]
add mapped point output_spikes[61] output_spikes[61]
add mapped point output_spikes[60] output_spikes[60]
add mapped point output_spikes[59] output_spikes[59]
add mapped point output_spikes[58] output_spikes[58]
add mapped point output_spikes[57] output_spikes[57]
add mapped point output_spikes[56] output_spikes[56]
add mapped point output_spikes[55] output_spikes[55]
add mapped point output_spikes[54] output_spikes[54]
add mapped point output_spikes[53] output_spikes[53]
add mapped point output_spikes[52] output_spikes[52]
add mapped point output_spikes[51] output_spikes[51]
add mapped point output_spikes[50] output_spikes[50]
add mapped point output_spikes[49] output_spikes[49]
add mapped point output_spikes[48] output_spikes[48]
add mapped point output_spikes[47] output_spikes[47]
add mapped point output_spikes[46] output_spikes[46]
add mapped point output_spikes[45] output_spikes[45]
add mapped point output_spikes[44] output_spikes[44]
add mapped point output_spikes[43] output_spikes[43]
add mapped point output_spikes[42] output_spikes[42]
add mapped point output_spikes[41] output_spikes[41]
add mapped point output_spikes[40] output_spikes[40]
add mapped point output_spikes[39] output_spikes[39]
add mapped point output_spikes[38] output_spikes[38]
add mapped point output_spikes[37] output_spikes[37]
add mapped point output_spikes[36] output_spikes[36]
add mapped point output_spikes[35] output_spikes[35]
add mapped point output_spikes[34] output_spikes[34]
add mapped point output_spikes[33] output_spikes[33]
add mapped point output_spikes[32] output_spikes[32]
add mapped point output_spikes[31] output_spikes[31]
add mapped point output_spikes[30] output_spikes[30]
add mapped point output_spikes[29] output_spikes[29]
add mapped point output_spikes[28] output_spikes[28]
add mapped point output_spikes[27] output_spikes[27]
add mapped point output_spikes[26] output_spikes[26]
add mapped point output_spikes[25] output_spikes[25]
add mapped point output_spikes[24] output_spikes[24]
add mapped point output_spikes[23] output_spikes[23]
add mapped point output_spikes[22] output_spikes[22]
add mapped point output_spikes[21] output_spikes[21]
add mapped point output_spikes[20] output_spikes[20]
add mapped point output_spikes[19] output_spikes[19]
add mapped point output_spikes[18] output_spikes[18]
add mapped point output_spikes[17] output_spikes[17]
add mapped point output_spikes[16] output_spikes[16]
add mapped point output_spikes[15] output_spikes[15]
add mapped point output_spikes[14] output_spikes[14]
add mapped point output_spikes[13] output_spikes[13]
add mapped point output_spikes[12] output_spikes[12]
add mapped point output_spikes[11] output_spikes[11]
add mapped point output_spikes[10] output_spikes[10]
add mapped point output_spikes[9] output_spikes[9]
add mapped point output_spikes[8] output_spikes[8]
add mapped point output_spikes[7] output_spikes[7]
add mapped point output_spikes[6] output_spikes[6]
add mapped point output_spikes[5] output_spikes[5]
add mapped point output_spikes[4] output_spikes[4]
add mapped point output_spikes[3] output_spikes[3]
add mapped point output_spikes[2] output_spikes[2]
add mapped point output_spikes[1] output_spikes[1]
add mapped point output_spikes[0] output_spikes[0]

//inout ports




//Sequential Pins
add mapped point dummy[0]/q dummy_reg[0]/QN 
add mapped point dummy[1]/q dummy_reg[1]/QN 
add mapped point dummy[2]/q dummy_reg[2]/QN 
add mapped point dummy[3]/q dummy_reg[3]/QN 
add mapped point dummy[4]/q dummy_reg[4]/QN 
add mapped point dummy[5]/q dummy_reg[5]/QN 
add mapped point dummy[6]/q dummy_reg[6]/QN 
add mapped point dummy[7]/q dummy_reg[7]/QN 
add mapped point dummy[8]/q dummy_reg[8]/QN 
add mapped point dummy[9]/q dummy_reg[9]/QN 
add mapped point dummy[10]/q dummy_reg[10]/QN 
add mapped point dummy[11]/q dummy_reg[11]/QN 
add mapped point dummy[12]/q dummy_reg[12]/QN 
add mapped point dummy[13]/q dummy_reg[13]/QN 
add mapped point dummy[14]/q dummy_reg[14]/QN 
add mapped point dummy[15]/q dummy_reg[15]/QN 
add mapped point dummy[16]/q dummy_reg[16]/QN 
add mapped point dummy[17]/q dummy_reg[17]/QN 
add mapped point dummy[18]/q dummy_reg[18]/QN 
add mapped point dummy[19]/q dummy_reg[19]/QN 
add mapped point dummy[20]/q dummy_reg[20]/QN 
add mapped point dummy[21]/q dummy_reg[21]/QN 
add mapped point dummy[22]/q dummy_reg[22]/QN 
add mapped point dummy[23]/q dummy_reg[23]/QN 
add mapped point dummy[24]/q dummy_reg[24]/QN 
add mapped point dummy[25]/q dummy_reg[25]/QN 
add mapped point dummy[26]/q dummy_reg[26]/QN 
add mapped point dummy[27]/q dummy_reg[27]/QN 
add mapped point dummy[28]/q dummy_reg[28]/QN 
add mapped point dummy[29]/q dummy_reg[29]/QN 
add mapped point dummy[30]/q dummy_reg[30]/QN 
add mapped point dummy[31]/q dummy_reg[31]/QN 
add mapped point dummy[32]/q dummy_reg[32]/QN 
add mapped point dummy[33]/q dummy_reg[33]/QN 
add mapped point dummy[34]/q dummy_reg[34]/QN 
add mapped point dummy[35]/q dummy_reg[35]/QN 
add mapped point dummy[36]/q dummy_reg[36]/QN 
add mapped point dummy[37]/q dummy_reg[37]/QN 
add mapped point dummy[38]/q dummy_reg[38]/QN 
add mapped point dummy[39]/q dummy_reg[39]/QN 
add mapped point dummy[40]/q dummy_reg[40]/QN 
add mapped point dummy[41]/q dummy_reg[41]/QN 
add mapped point dummy[42]/q dummy_reg[42]/QN 
add mapped point dummy[43]/q dummy_reg[43]/QN 
add mapped point dummy[44]/q dummy_reg[44]/QN 
add mapped point dummy[45]/q dummy_reg[45]/QN 
add mapped point dummy[46]/q dummy_reg[46]/QN 
add mapped point dummy[47]/q dummy_reg[47]/QN 
add mapped point dummy[48]/q dummy_reg[48]/QN 
add mapped point dummy[49]/q dummy_reg[49]/QN 
add mapped point dummy[50]/q dummy_reg[50]/QN 
add mapped point dummy[51]/q dummy_reg[51]/QN 
add mapped point dummy[52]/q dummy_reg[52]/QN 
add mapped point dummy[53]/q dummy_reg[53]/QN 
add mapped point dummy[54]/q dummy_reg[54]/QN 
add mapped point dummy[55]/q dummy_reg[55]/QN 
add mapped point dummy[56]/q dummy_reg[56]/QN 
add mapped point dummy[57]/q dummy_reg[57]/QN 
add mapped point dummy[58]/q dummy_reg[58]/QN 
add mapped point dummy[59]/q dummy_reg[59]/QN 
add mapped point dummy[60]/q dummy_reg[60]/QN 
add mapped point dummy[61]/q dummy_reg[61]/QN 
add mapped point dummy[62]/q dummy_reg[62]/QN 
add mapped point dummy[63]/q dummy_reg[63]/QN 



//Black Boxes
